### ISSUE TITLE
As a visitor I want a defined URL and E-Mail to contact

### ISSUE THREAD

**Issue by ohnewein** [noi-techpark/software-website#19]
We have 2 URLs now:
- software.bz.it
- freesoftwarelab.noi.bz.it

Clicking on the website logo, the user will land on software.bz.it, even if he started from freesoftwarelab.noi.bz.it Please make freesoftwarelab.noi.bz.it the default.

In contacts we publish info@software.bz.it as contact address. Please activate and publish info@freesoftwarelab.noi.bz.it

**Comment by useppi** [comment]
solved
