### ISSUE TITLE
Contact Form: Required fields ignored

### ISSUE THREAD

**Issue by ohnewein** [noi-techpark/software-website#26]
Even if some required fields are not filled out, the "Send message" reports "Your request has been processed."

It shouldn't be possible to send a request, without filling out all required fields. Right?

Btw. Don't make the Phone Number a required field.

![Screenshot from 2019-11-19 09-51-16](https://user-images.githubusercontent.com/414797/69131273-61d49680-0ab2-11ea-9089-4e91e95d7a8e.png)

**Comment by useppi** [comment]
solved
