### ISSUE TITLE
As PM of Free Software Lab, I want that everytime a "book service" button is clicked an automatic email with all information is send to freesoftwarelab@noi.bz.it

### ISSUE THREAD

**Issue by LucaMiotto** [noi-techpark/software-website#28]
After compiling the form, a user of the lab will click the button Book service at the end of the page and an email should be send to freesoftwarelab@noi.bz.it with all the information contained in the form (Could also be used info@software.bz.it).

E.g.: https://freesoftwarelab.noi.bz.it/services/app_usability/

**Comment by bertolla** [comment]
Mail client is set up and running on test environement:
http://it.bz.freesoftwarelab.test.s3-website-eu-west-1.amazonaws.com/

This version also contains the newest changes send in by Ulli.

Mails will be send to info@software.bz.it, if you compile the forms.

**Comment by LucaMiotto** [comment]
Tested, it works. Just missing the field for type of service ([Issue 31](https://github.com/noi-techpark/software-website/issues/31)).

**Comment by LucaMiotto** [comment]
Type of service is also included now. We can close it.
