### ISSUE TITLE
Absolute url paths

### ISSUE THREAD

**Issue by bertolla** [noi-techpark/software-website#30]
Some links which route inside the webpage are absolute.
Is it possible to make them relative, so the testing environment stops linking to the production env?
![absolute](https://user-images.githubusercontent.com/3582457/70427597-52bf8380-1a75-11ea-833e-620e80348671.png)

**Comment by lelebus** [comment]
You just have to change the base URL in the config file of the site

**Comment by bertolla** [comment]
That does the job, even thought it's more like a workaround and wouldn't work anymore if more than one domain would point to the site.
A solution where paths can be set relatively would be more appropriate, but maybe Hugo does not allow that.

**Comment by useppi** [comment]
To close as discussed with Luca
