### ISSUE TITLE
Services Form post missing field

### ISSUE THREAD

**Issue by bertolla** [noi-techpark/software-website#31]
The actual form post does not contain the service name, which the request is asking for.
Can it be send in the post form as hidden input field?

**Comment by lelebus** [comment]
The service form field is implemented like all the other fields of the form. The only difference is that it does not appear to the final user, because it is of type hidden.
`<input type="hidden" id="service" name="service" value="{{ .Title }}">`

**Comment by LucaMiotto** [comment]
That's the point, we cannot find that line in the code. Could you give us information where it should be? I think maybe we have some discrepancy between your code and our code.

**Comment by lelebus** [comment]
You were several versions behind. Code in recent pull request should solve issue

**Comment by LucaMiotto** [comment]
Tested and it works.
